<a href="https://colab.research.google.com/github/arpan02-code/data-wrangling-lab/blob/main/Numpy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating numpy
arrya

In [1]:
import numpy as np


In [4]:
a = np.array([1,2,3,4,5])

In [5]:
print(a)

[1 2 3 4 5]


creating 2D nad 3D array

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
print (b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
c = np.array([[[1,2,3,4],[1,3,4,5],[4,5,6,7]]],dtype = np.float128)

In [10]:
print (c)

[[[1 2 3 4]
  [1 3 4 5]
  [4 5 6 7]]]


data type of array

In [15]:
print(c.dtype)

float128


to arrange 1 to 10

In [18]:
print(np.arange(1,11))


[ 1  2  3  4  5  6  7  8  9 10]


to give a shap for it - reshap()

In [23]:
print(np.arange(1, 11).reshape(2, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


OR

In [24]:
x = np.arange(1,11)
print(x.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array of all elements 1 and 0

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

random method

In [29]:
np.random.rand(3,4)

array([[0.15501779, 0.46524203, 0.87329096, 0.55531044],
       [0.71463434, 0.25447669, 0.9324474 , 0.86168411],
       [0.86908667, 0.38151098, 0.84158557, 0.01858305]])

In [34]:
np.random.choice(['Apple', 'Banana', 'Mango'], size=2)

array(['Apple', 'Banana'], dtype='<U6')

In [35]:
np.random.randn(4,7)

array([[-0.87418527, -2.14726325, -0.09764794,  0.62116454, -2.32603352,
        -0.04757718, -1.21439186],
       [ 0.37934797,  1.79582718, -0.58677775,  2.63981111, -0.53580622,
         1.17072839,  0.2009045 ],
       [-0.32324994, -0.26373617,  0.05657946, -2.50448273,  0.34397421,
        -0.13011959, -0.11147777],
       [ 0.26101568, -0.95521496, -0.34719252,  1.67271433,  0.21536706,
        -0.61999366, -1.44199862]])

In [37]:
m=np.random.seed(5) # act as a checkpoint
print (m)

None


In [40]:
print(np.random.shuffle(x))

None
